### ISSUE TITLE
Eiskalt DC crashed on Raspberry Pi 2B with Rasbian

### ISSUE THREAD

**Issue by Infinity666** [eiskaltdcpp/eiskaltdcpp#315]
The Client crashed when rehash th Filelist or over 12 Hours without any Error.

**Comment by tehnick** [comment]
What version of program do you use?

**Comment by Infinity666** [comment]
2.2.6.4 this Version under Rasbian under Ubuntu Mate 15.04 on my raspberry pi 2b eiskalt works fine.

**Comment by tehnick** [comment]
Ok, your bug is already fixed in master branch and in git tag v2.2.10, see: f29fa588 and f9be84e9. Also these patches are available for stable release v2.2.9 in my packages for Debian and Ubuntu: https://github.com/tehnick/eiskaltdcpp-debian/blob/debian/2.2.9-3/debian/patches/fix_TigerHash_on_ARM.patch
