### ISSUE TITLE
Importing IP-Filter Blocklist?

### ISSUE THREAD

**Issue by WebBuddha** [eiskaltdcpp/eiskaltdcpp#360]
How to import an complete IP-Filter Blocklist with IP-adress ranges?

**Comment by Korb** [comment]
I try to import a file with strings like

```
000.000.000.000 - 000.255.255.255 , 000 , Bogon
001.002.004.000 - 001.002.004.255 , 000 , China Internet Information Center (CNNIC)
001.002.008.000 - 001.002.008.255 , 000 , China Internet Information Center (CNNIC)
001.009.096.105 - 001.009.096.105 , 000 , Botnet on Telekom Malaysia
001.009.102.251 - 001.009.102.251 , 000 , Botnet on Telekom Malaysia
```

and the application does not react in any way - the list is not imported, and no error messages appear. The same thing happens if I specify in the "Add" field the path to a local file or its [remote copy](http://list.iblocklist.com/?list=ru&fileformat=p2p&archiveformat=7z).

EiskaltDC++2.4.2, Microsoft Windows 10.0.19044.1949
