### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by dennwc** [eiskaltdcpp/eiskaltdcpp#393]
Github and Git release tags are out of sync with the latest application version in the manifest file.

Will be nice to tag each release in Git and/or Github, including the current version.

Also, it will be nice to change build scripts to use `git describe --tags` to detect the version.

**Comment by tehnick** [comment]
> Github and Git release tags are out of sync with the latest application version in the manifest file.

Which manifest file do you mean?

> Will be nice to tag each release in Git and/or Github, including the current version.

All git tags are in proper places. Last official release was [v2.2.9](https://sourceforge.net/projects/eiskaltdcpp/files/Sources/). Last git tag -- [v2.2.10](https://github.com/eiskaltdcpp/eiskaltdcpp/releases/tag/v2.2.10). Current development version is `v2.4.0` and it will be released once it ready. Version `v2.3.0` was skipped due to problems with versions scheme which was used in the past.

All this is even documented in [ChangeLog](https://github.com/eiskaltdcpp/eiskaltdcpp/blob/master/ChangeLog.txt) which misses a lot of other changes (and this is one of reasons why release is such delayed).

> Also, it will be nice to change build scripts to use `git describe --tags` to detect the version.

Which build scripts are you talking about? Git repo includes a lot of outdated files. But all actual scripts already use `git describe --tags` to detect the version, see:
https://github.com/eiskaltdcpp/eiskaltdcpp/blob/291ee707/CMakeLists.txt#L255

And this version schema is used in all actual builds, for example:
https://tracker.debian.org/pkg/eiskaltdcpp
https://launchpad.net/ubuntu/+source/eiskaltdcpp
https://launchpad.net/~tehnick/+archive/ubuntu/direct-connect-devel
https://sourceforge.net/projects/eiskaltdcpp/files/macOS/devel/
https://aur.archlinux.org/packages.php?K=eiskaltdcpp

**Comment by dennwc** [comment]
Sorry, I've been confused by the number of commits in the `master` since the last release and the message in the changelog. And thanks for a detailed answer.
