### ISSUE TITLE
Hilight on already shared folders does not work.

### ISSUE THREAD

**Issue by wuseman** [eiskaltdcpp/eiskaltdcpp#410]
When I search for a folder in my already shared share I cant get the folder hilighted. I have set it to be highlighted with and without transparency and with red color but under search none of my folders or files are colorized and neither if I browsing a filelist, have I missed something or does the feature not work anymore?

Regards

**Comment by wuseman** [comment]
I figure out that I had to enable already shared files also under the hidden panel under search, now it works for files, how can I enable this for folders aswell? Maybe this is not possible atm?

**Comment by ValdikSS** [comment]
Did it work earlier? If it did, in which version?

**Comment by tehnick** [comment]
> I figure out that I had to enable already shared files also under the hidden panel under search, now it works for files

Yes, this option is disabled by default to decrease the CPU usage.

> how can I enable this for folders aswell?

Unfortunately, this is not possible. Files are checked by their unique TTH, but for folders there is no such information due to DC protocol features. Any any workaround like comparing the amount and equality of files in folder will be slow and very expensive (CPU usage).
