### ISSUE TITLE
The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated

### ISSUE THREAD

**Issue by ValdikSS** [eiskaltdcpp/eiskaltdcpp#411]
```
In file included from /usr/include/boost/detail/endian.hpp:9,
                 from /home/valdikss/eiskaltdcpp-qt/src/eiskaltdcpp-master/dcpp/TigerHash.cpp:37:
/usr/include/boost/predef/detail/endian_compat.h:11:161: note: #pragma message: The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead
   11 | #pragma message("The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead")
```

**Comment by tehnick** [comment]
Yep, I hope one time rewrite the rest of code onto pure C++. See:
https://github.com/eiskaltdcpp/eiskaltdcpp/blob/a3a9f3eb/TODO#L8
A lot of work is already done.

As for `BOOST_*_ENDIAN` and `BOOST_BYTE_ORDER`, this will be rewritten using `cmake` features, because I have not found other way to check bytes order at build time.

**Comment by tehnick** [comment]
Fixed in https://github.com/eiskaltdcpp/eiskaltdcpp/commit/c31d08b5b6ebdb955db1d7b071f188f40546a0a5
